[build]
  publish = "dist/next-train/browser"
  command = "npm run build:production"

[[redirects]]
  from = "/trafiklabApi/*"
  to = "https://transport.integration.sl.se/v1/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}

# Firebase Auth proxy - MUST come before the catch-all redirect
[[redirects]]
  from = "/__/auth/*"
  to = "https://upcoming-departures.firebaseapp.com/__/auth/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "22.16.0"

# Cache control for static assets (1 week)
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=604800"

# Cache control for index.html
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
